name: school_todo_list
description: "Mobile application TODO list."
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  uuid: ^4.4.0
  intl: ^0.19.0
  logger: ^2.3.0
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  sqflite: ^2.3.3+1
  provider: ^6.1.2
  get_it: ^7.7.0
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.3
  freezed_annotation: ^2.4.4
  equatable: ^2.0.5
  firebase_core: ^3.2.0
  firebase_remote_config: ^5.0.3
  firebase_analytics: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  retrofit_generator: ^8.1.0
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter
  freezed: ^2.5.2

flutter:
  uses-material-design: true
